### ISSUE TITLE
Many -Wconversion warnings

### ISSUE THREAD

**Issue by niyaznigmatullin** [ifsmirnov/jngen#5]
I don't know, whether it's good or bad, there are many -Wconversion warnings in jngen.h. Fixing them would make life easier for those who use -Wconversion.

**Comment by ifsmirnov** [comment]
IMO it is one of the most useless warnings I've ever known :) Still, it shouldn't be hard to fix, I'll do it.

**Comment by ifsmirnov** [comment]
Well, this warning shows up at _too_ many places. In clang, -Wconversion enables -Wsign-conversion as well, and you cannot subscript vector with int:

```
int x;
vector<int> a;
a[x] = 1; // warning
a[static_cast<size_t>(x)] = 1; // ok
```

I don't want to add such boilerplate to the library so I wrapped the source code with pragmas supressing the warning: 22a2d9b481316bb036cf4279bb060d7670911c82.
